/** Positions use percentages of the full artwork, not the cropped viewport.
 * Drawing anchors and clickable regions come from this same editable source.
 */
const desktopHits = {
  northstar: [15, 20], base: [30, 25], trailmap: [9, 18], news: [5, 11],
  gym: [11.5, 14.5], summit: [14, 18], refuge: [12.5, 14.5], shop: [14.5, 19],
};
const mobileHits = {
  northstar: [18, 15], base: [34, 26], trailmap: [16, 12], news: [10, 8],
  gym: [15.5, 11.5], summit: [17, 12], refuge: [18, 10], shop: [20, 12.5],
};

function layout(width, height, points, hits) {
  return {
    width, height,
    landmarks: Object.fromEntries(Object.entries(points).map(([name, [x, y]]) =>
      [name, { x, y, hitWidth: hits[name][0], hitHeight: hits[name][1] }],
    )),
  };
}

export const layouts = {
  sunny: {
    horizontal: layout(1672, 941, {
      northstar: [14.3, 23], base: [17, 85], trailmap: [71, 47], news: [75, 86],
      gym: [53, 75], summit: [58, 9], refuge: [61, 39], shop: [85, 71],
    }, desktopHits),
    vertical: layout(941, 1672, {
      northstar: [17, 13], base: [17, 83], trailmap: [83, 42], news: [68, 77],
      gym: [47, 65], summit: [60, 7], refuge: [68, 34], shop: [80, 66],
    }, mobileHits),
  },
  rainy: {
    horizontal: layout(1672, 941, {
      northstar: [25, 8.5], base: [14.5, 85], trailmap: [71, 49], news: [75, 86],
      gym: [52, 75], summit: [57, 8], refuge: [61, 38], shop: [85, 71],
    }, desktopHits),
    vertical: layout(941, 1672, {
      northstar: [17.5, 13], base: [15, 80], trailmap: [86, 38], news: [68, 76],
      gym: [50, 62], summit: [60, 8], refuge: [68, 32], shop: [79, 63],
    }, mobileHits),
  },
  snowy: {
    horizontal: layout(1672, 941, {
      northstar: [14.3, 24], base: [15.5, 87], trailmap: [75.5, 45], news: [74, 86.5],
      gym: [53, 78], summit: [58, 7], refuge: [62, 39], shop: [85, 72],
    }, desktopHits),
    vertical: layout(941, 1672, {
      northstar: [20, 14], base: [19, 83], trailmap: [86, 44], news: [69, 79],
      gym: [46, 68], summit: [66, 9], refuge: [70, 37], shop: [80, 69],
    }, mobileHits),
  },
};

export function hotspotStyles() {
  const selectors = { news: "mailbox" };
  const rules = (orientation) => Object.entries(layouts).map(([weather, variants]) =>
    Object.entries(variants[orientation].landmarks).map(([name, point]) =>
      `.experience[data-weather="${weather}"] .hotspot--${selectors[name] || name} { --x: ${point.x}%; --y: ${point.y}%; --hit-w: ${point.hitWidth}%; --hit-h: ${point.hitHeight}%; }`,
    ).join("\n"),
  ).join("\n\n");
  return `/* Generated by npm run build:scenes. Edit scripts/scenes/layouts.mjs. */\n${rules("horizontal")}\n\n@media (max-width: 700px) {\n${rules("vertical")}\n}\n`;
}
